--- 
- 
  name: "start httpd"
  service: 
    enabled: true
    name: httpd
    state: started
- 
  name: "start apache2"
  service: 
    enabled: true
    name: apache2
    state: started
- 
  name: "restart httpd"
  service: 
    enabled: true
    name: httpd
    state: restarted
- 
  name: "restart apache2"
  service: 
    enabled: true
    name: apache2
    state: restarted

