---
- name: Install httpd package
  hosts: all
  become: true
  vars:
     port: 8082
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start httpd
    
  - name: Ensure the default httpd port is {{port}}
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{port}}
    when: ansible_os_family == "RedHat"
    notify: restart httpd
    
  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2
  
  - name: copy file
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

  - name: Ensure the default Apache2 port is {{port}}
    lineinfile:
       path: /etc/apache2/ports.conf
       regexp: '^Listen '
       insertafter: '^#Listen '
       line: Listen {{port}}
    when: ansible_os_family == "Debian"
    notify: restart apache2

  handlers:
  - name: start httpd
    service:
      name: httpd
      state: started
      enabled: yes

  - name: start apache2
    service:
      name: apache2
      state: started
      enabled: yes
      
  - name: restart httpd
    service:
      name: httpd
      state: restarted
      enabled: yes
      
  - name: restart apache2
    service:
      name: apache2
      state: restarted
      enabled: yes

