---
- name: Uninstall httpd package
  hosts: dbserver
  become: true
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
      enabled: no
  - name: Uninstall httpd
    yum:
      name: httpd
      state: removed
